// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFEkM4JBR4I4ImMMe8ncnFpkLhvk5Uug',
    appId: '1:606806516800:android:6a4ae04913d810ba',
    messagingSenderId: '606806516800',
    projectId: 'lichviet-free',
    databaseURL: 'https://lichviet-free.firebaseio.com',
    storageBucket: 'lichviet-free.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSVa_0joKsWwHcVtLy5HJRgFvD7sK4Yrg',
    appId: '1:606806516800:ios:96bde29cce0bfdca',
    messagingSenderId: '606806516800',
    projectId: 'lichviet-free',
    databaseURL: 'https://lichviet-free.firebaseio.com',
    storageBucket: 'lichviet-free.appspot.com',
    androidClientId:
        '606806516800-15kmik95luasvtukcavbtfl3blpnjo3n.apps.googleusercontent.com',
    iosClientId:
        '606806516800-ig25nv7hooklvk79rk7gbj2dapc1homo.apps.googleusercontent.com',
    iosBundleId: 'com.vietlotus.lichvietfree',
  );
}
