name: lichviet_flutter_base
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/Lich-Viet/lichviet-flutter-base.git

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mz_rsa_plugin: ^0.0.4
  connectivity_plus: ^3.0.2
  get_it: ^7.2.0
  tripledes_nullsafety: ^1.0.3
  encrypt: ^5.0.1
  shake: ^2.1.0
  http: ^0.13.5
  intl: ^0.17.0
  rxdart: ^0.27.7
  flutter_screenutil: ^5.6.0
  path_provider: ^2.0.11
  package_info_plus: ^3.0.2
  cached_network_image: ^3.2.3
  device_info_plus: ^8.0.0
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.1.1
  json_annotation: ^4.7.0
  dio: ^4.0.6
  quiver: ^3.1.0
  equatable: ^2.0.3
  tiengviet: ^0.5.0
  get: ^4.6.5
  # google_mobile_ads: 
  #   git:
  #     url: https://github.com/tienld/googleads-mobile-flutter.git
  #     path: packages/google_mobile_ads/
  zoom_widget: ^0.2.1
  firebase_analytics: ^9.3.8
  firebase_crashlytics: ^2.8.10
  firebase_performance: ^0.8.3+3
  hive: ^2.2.3
  #google_mobile_ads: ^2.3.0
  google_mobile_ads:
   git:
    url: https://github.com/pvddeveloper/googleads-mobile-flutter.git
    path: packages/google_mobile_ads
  lifecycle: 0.6.0

  html: 

  # Plugins for parsing css
  csslib: 

  # Plugins for rendering the <table> tag.
  flutter_layout_grid:

  # Plugins for rendering the <video> tag.
  video_player: 
  chewie: 

  # Plugin for rendering the <iframe> tag.
  webview_flutter: '>=2.0.4 <3.0.0'

  # Plugins for rendering the <audio> tag.
  chewie_audio: 

  # Plugins for rendering the <svg> tag.
  flutter_svg:

  # Plugin for rendering MathML
  flutter_math_fork: 

  # plugin for firstWhereOrNull extension on lists
  collection:

  # plugin to convert integers to numerals
  numerus: '>=1.1.1 <2.0.0'
  firebase_remote_config: ^2.0.20
  applovin_max: ^2.4.3
 #  git:
  #  url: https://github.com/pvddeveloper/AppLovin-MAX-Flutter.git

dev_dependencies:
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  module:
    androidX: true
  

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/back.svg
    - assets/bubbles.svg
    - assets/types/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
